# Generated by Django 4.2.7 on 2023-11-08 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taverna', '0002_post_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
