# Generated by Django 4.2.7 on 2023-11-16 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taverna', '0003_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='file',
        ),
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(choices=[('TA', 'Такни'), ('HE', 'Хилы'), ('DD', 'ДД'), ('TR', 'Торговцы'), ('GM', 'Гилдмастеры'), ('QG', 'Квестгиверы'), ('BL', 'Кузнецы'), ('TN', 'Кожевники'), ('PM', 'Зельевары'), ('SM', 'Мастера заклинаний'), ('EV', 'Ивент'), ('GU', 'Гайд')], max_length=2, unique=True),
        ),
    ]
